//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.06.15 at 06:24:27 PM EEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://liwaaaudi.viko.lt/task-2", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package lt.viko.liwaaaudi.task_2;
